package tiktok

import (
	"crypto/md5"
)

// X-Bogus is the request-signing parameter TikTok's web client appends to the
// query string of its undocumented JSON endpoints. It is a deterministic
// transform over the exact query string, the User-Agent, and a Unix timestamp,
// using two MD5 passes, an RC4 keystream, and a custom base64 alphabet. This is
// a pure-Go port of the publicly reverse-engineered algorithm; it is verified
// byte-for-byte against a fixed input→output vector in the tests.
//
// # Honest scope
//
// X-Bogus is necessary but, as of 2025/2026, NOT sufficient on its own. TikTok
// additionally enforces a browser-minted msToken cookie (generated by its
// webmssdk.js via canvas/WebGL/audio fingerprinting) and a newer X-Gnarly
// signature that depend on a real JavaScript runtime. A correct X-Bogus with no
// valid msToken still receives an HTTP 200 with an empty body (the anti-bot
// block). This client therefore signs correctly and accepts a caller-supplied
// msToken, but cannot forge the fingerprint-derived tokens in pure Go.

// xbShiftAlphabet is the custom base64 alphabet the final X-Bogus encoding uses.
const xbShiftAlphabet = "Dkdpgh4ZKsQB80/Mfvw36XI1R25-WUAlEi7NLboqYTOPuzmFjJnryx9HVGcaStCe"

// xbStdAlphabet is the standard base64 alphabet (with '=' padding at index 64)
// used for the intermediate User-Agent encoding.
const xbStdAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="

// xbMagic is the constant salt TikTok mixes into the signature.
const xbMagic = 536919696

// XBogus computes TikTok's X-Bogus signature for the given query string and
// User-Agent at the given Unix time (seconds). The returned value is the raw
// 28-character parameter (without the leading "X-Bogus=").
func XBogus(query, userAgent string, unixSeconds int64) string {
	md5Query := doubleMD5([]byte(query))
	md5Data := doubleMD5(nil) // request body is empty for GET endpoints
	uaEnc := customBase64(rc4(([]byte)(userAgent), []byte{0, 1, 14}), xbStdAlphabet)
	md5UA := md5.Sum([]byte(uaEnc))

	ts := unixSeconds
	salt := []int{
		int(ts),
		xbMagic,
		64,
		0,
		1,
		14,
		int(md5Query[14]), int(md5Query[15]),
		int(md5Data[14]), int(md5Data[15]),
		int(md5UA[14]), int(md5UA[15]),
	}
	// big-endian bytes of the timestamp, then of the magic constant.
	for shift := 24; shift >= 0; shift -= 8 {
		salt = append(salt, int(ts>>uint(shift))&0xff)
	}
	for shift := 24; shift >= 0; shift -= 8 {
		salt = append(salt, (xbMagic>>uint(shift))&0xff)
	}
	// checksum over salt[3:] (the current 20 elements), seeded with 64.
	chk := 64
	for _, v := range salt[3:] {
		chk ^= v
	}
	salt = append(salt, chk, 255)

	scrambled := xbScramble(xbFilter(salt))
	enc := rc4(scrambled, []byte{255})
	payload := append([]byte{0x02, 0xff}, enc...)
	return customBase64(payload, xbShiftAlphabet)
}

// doubleMD5 returns md5(md5(b)) as a 16-byte digest.
func doubleMD5(b []byte) [16]byte {
	first := md5.Sum(b)
	return md5.Sum(first[:])
}

// rc4 returns the RC4 keystream XOR of data under key, matching TikTok's
// reference (a plain RC4 with the given key schedule).
func rc4(data, key []byte) []byte {
	s := make([]int, 256)
	for i := range s {
		s[i] = i
	}
	j := 0
	for i := 0; i < 256; i++ {
		j = (j + s[i] + int(key[i%len(key)])) % 256
		s[i], s[j] = s[j], s[i]
	}
	out := make([]byte, len(data))
	a, b := 0, 0
	for i := 0; i < len(data); i++ {
		a = (a + 1) % 256
		b = (b + s[a]) % 256
		s[a], s[b] = s[b], s[a]
		out[i] = data[i] ^ byte(s[(s[a]+s[b])%256])
	}
	return out
}

// customBase64 encodes src with the given 64/65-character alphabet, replicating
// the reference encoder exactly — including its handling of a short trailing
// group, where a group of fewer than three bytes is emitted from the first byte
// alone followed by two pad characters (alphabet index 64). Callers whose input
// length is a multiple of three (the final X-Bogus payload) never hit the pad
// path, so a 64-character alphabet is safe there.
func customBase64(src []byte, alphabet string) string {
	out := make([]byte, 0, (len(src)+2)/3*4)
	for i := 0; i < len(src); i += 3 {
		if i+2 < len(src) {
			n1, n2, n3 := int(src[i]), int(src[i+1]), int(src[i+2])
			out = append(out,
				alphabet[n1>>2],
				alphabet[(3&n1)<<4|n2>>4],
				alphabet[(15&n2)<<2|n3>>6],
				alphabet[63&n3],
			)
			continue
		}
		n1 := int(src[i])
		out = append(out, alphabet[n1>>2], alphabet[(3&n1)<<4], alphabet[64], alphabet[64])
	}
	return string(out)
}

// xbFilter reorders the salt array by the reference's fixed 1-based index
// pattern, yielding the 19 values the scramble step consumes.
func xbFilter(salt []int) []int {
	order := []int{3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 4, 6, 8, 10, 12, 14, 16, 18, 20}
	out := make([]int, len(order))
	for i, p := range order {
		out[i] = salt[p-1]
	}
	return out
}

// xbScramble interleaves the first ten and last nine filtered values into the
// 19-byte string RC4 then encrypts.
func xbScramble(v []int) []byte {
	// v has 19 elements: a..j = v[0:10], k..s = v[10:19].
	idx := []int{0, 10, 1, 11, 2, 12, 3, 13, 4, 14, 5, 15, 6, 16, 7, 17, 8, 18, 9}
	out := make([]byte, len(idx))
	for i, p := range idx {
		out[i] = byte(v[p])
	}
	return out
}
